apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: audit-api
  namespace: campus
spec:
  hosts:
    - "*"
  gateways:
    - campus-api
  http:
    - match:
        - uri:
            prefix: /api/audit/
          method:
            exact: GET
      rewrite:
        uri: /
      route:
        - destination:
            host: audit.campus.svc.cluster.local
            port:
              number: 8000
      retries:
        attempts: 2
        perTryTimeout: 3s
        retryOn: connect-failure,reset,refused-stream,503
      timeout: 10s
    - match:
        - uri:
            prefix: /api/audit/
      rewrite:
        uri: /
      route:
        - destination:
            host: audit.campus.svc.cluster.local
            port:
              number: 8000
      timeout: 15s

