service: bookings
replicas: 2
image:
  repository: 192.168.49.2:32000/campusreserve
  tag: ci-d936fcd8719e-37399724035-1
  pullPolicy: IfNotPresent
credentialsSecret: campus-credentials
connections:
  kafka: campus-kafka-kafka-bootstrap:9092
  redis: redis://valkey:6379
  postgres: postgres:5432
  mongoHot: mongodb://mongo-hot:27017
  mongoCold: mongodb://mongo-cold:27017
