apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: campus-rooms
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MikaTwentyTwo/Software-Engineering-task-1.git
    targetRevision: main
    path: platform/charts/campus-rooms
    helm:
      releaseName: campus-rooms
  destination:
    server: https://kubernetes.default.svc
    namespace: campus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
